version: '3'
services:
  consul-server:
    image: consul:latest
    container_name: consul-server
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - SERVICE_IGNORE=true
      - CONSUL_ALLOW_PRIVILEGED_PORTS=true
    cap_add:
      - ALL
    volumes:
      - ./consul-config:/consul/config
    ports:
      - 8500:8500/tcp
      - 8600:53/tcp
      - 8600:53/udp
  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    depends_on:
      - consul-server
#    command: ["-resync=30", "-cleanup=true", "-ip=127.0.0.1", "-retry-attempts=-1", "consul://consul-server:8500"]
    command: ["-resync=30", "-cleanup=true", "-tags=docker-ip", "-internal", "-retry-attempts=-1", "consul://consul-server:8500"]
  consul-server-ttl:
    image: consul:latest
    container_name: consul-server-ttl
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - SERVICE_IGNORE=true
      - CONSUL_ALLOW_PRIVILEGED_PORTS=true
    volumes:
      - ./consul-config-ttl:/consul/config
    cap_add:
      - ALL
    ports:
      - 8501:8500/tcp
      - 8601:53/tcp
      - 8601:53/udp
  registrator-ttl:
    image: gliderlabs/registrator:latest
    container_name: registrator-ttl
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    depends_on:
      - consul-server
#    command: ["-resync=30", "-cleanup=true", "-ip=127.0.0.1", "-retry-attempts=-1", "consul://consul-server:8500"]
    command: ["-resync=30", "-cleanup=true", "-tags=docker-ip", "-internal", "-retry-attempts=-1", "-retry-interval=30000", "-ttl=120", "-ttl-refresh=60", "consul://consul-server-ttl:8500"]
  mysql-server-1:
    container_name: mysql-server-1
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.18
    ports:
      - "3301:3306"
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    depends_on:
      - registrator
  mysql-server-2:
    container_name: mysql-server-2
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.18
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3302:3306"
    depends_on:
      - registrator
  mysql-server-3:
    container_name: mysql-server-3
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.18
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3303:3306"
    depends_on:
      - registrator
  mysql-shell:
    container_name: mysql-shell
    env_file:
      - mysql-shell.env
    image: neumayer/mysql-shell-batch
    volumes:
        - ./scripts/:/scripts/
    depends_on:
      - registrator
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
  mysql-router-1:
    container_name: mysql-router-1
    env_file:
      - mysql-router.env
    environment:
      - SERVICE_TAGS=regionA
    image: mysql/mysql-router:8.0
    ports:
      - "6445:6446"
      - "7445:6447"
      - "64450:64460"
      - "54450:64470"
    depends_on:
      - registrator
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
      - mysql-shell
    restart: on-failure
  mysql-router-2:
    container_name: mysql-router-2
    env_file:
      - mysql-router.env
    image: mysql/mysql-router:8.0
    environment:
      - SERVICE_TAGS=regionA
    ports:
      - "6446:6446"
      - "7446:6447"
      - "64460:64460"
      - "54460:64470"
    depends_on:
      - registrator
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
      - mysql-shell
    restart: on-failure
  mysql-router-3:
    container_name: mysql-router-3
    env_file:
      - mysql-router.env
    environment:
      - SERVICE_TAGS=regionB
    image: mysql/mysql-router:8.0
    ports:
      - "6447:6446"
      - "7447:6447"
      - "64470:64460"
      - "54470:64470"
    depends_on:
      - registrator
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
      - mysql-shell
    restart: on-failure
